### ISSUE TITLE
Possible to add symbols to species binomen in phylogenetic tree?

### ISSUE THREAD

**Issue by kottewell** [Bartesto/gene_app#8]
This is a wishlist item and I'm not sure how feasible it is... We have collected additional information about the species in our study to provide some additional context e.g. IUCN redlist status, pest/pathogen, invasive species etc. I wondered if it would be possible to attach a small graphical symbol after each species name to represent the different IUCN categories etc in the phylogenetic tree? I can take a look through the collapsible tree package or look for examples on the web that might help.

**Comment by kottewell** [comment]
Looks like it might be better to do it by color fill, rather than graphical symbols.

**Comment by Bartesto** [comment]
Welcome @kottewell! Will look into it. A fill colour is probably most feasible.

**Comment by Bartesto** [comment]
Hi @kottewell and @RobynSh. I've made a start on a function to colour up the binoms according to their Red List status. Essentially I have a function that determines the number of members at each category (Phylum, Order etc) as you make different choices and then makes a vector of colours to apply to that category. Next step is to supply different colours dependent on the Red List category which will entail some logic statements. So two things before I progress this:

- It will be necessary to standardise the Red List categories. At present there are typos and what I think may also be abbreviations and long versions of the same category. It doesn't need to be perfect but it would be great if you guys could determine what categories you anticipate being in the final data and what form they might take.
- Also will need to know what colours you would like to apply to the categories? You could supply a different colour for each or we could just have colours for the most significant.

**Comment by kottewell** [comment]
Hi @Bartesto, sounds like great progress! I've just sent Robyn the cleaned IUCN data. The IUCN has colours for the Data Deficient and Extinct categories (see towards bottom of page https://www.iucnredlist.org/) so would be good to use these, but for the rest it seems common to colour them red to green as here: https://royalsocietypublishing.org/cms/asset/b8d8e8e2-664e-42b7-a4c5-ab30bd2f2f8d/rstb20140003f02.jpg 
We also have lots of NA's in the list. These could just be the default colour or white.

**Comment by Bartesto** [comment]
Will aim to use this scale then

![image](https://user-images.githubusercontent.com/7631947/141734153-503c4361-b04c-4ca9-ab58-a09dca5ff3d6.png)

**Comment by Bartesto** [comment]
- Data selected within app is now sorted hierarchically to enable consistent matching of unique binomens to appropriate IUCN Red List colours (colour blind friendly).
- Developed 3 functions to find errors in taxonomy (hierarchical or typo related).
- UI has been significantly upgraded with inline CSS.
