### ISSUE TITLE
Change order of realms

### ISSUE THREAD

**Issue by RobynSh** [Bartesto/gene_app#9]
Hi Bart - can we change the order of the shapefile realms in the plot? I think it might make it easier to select the terrestrial realms if the marine ones are plotted underneath. I've given it a go, and this tweak to your code seems to do the trick (i.e. when reading in the shapefiles):

#List terrestrial realms
Terrest <- c("Afrotropic", 
             "Antarctic",
             "Australasia", 
             "Indomalya", 
             "Nearctic",
             "Neotropic", 
             "Oceania", 
             "Palearctic",
             "Palearctic")

#Shape file for bioregions
shape <- sf::st_read("data/teow_meow_simplified.shp") %>%
  dplyr::rename(Bioregion = REALM) %>%
  dplyr::mutate(cols = as.factor(Bioregion), 
                Id = 1:length(Bioregion),
                PlotOrder = ifelse(Bioregion %in% Terrest, 2, 1)) %>%
  dplyr::arrange(PlotOrder)

**Comment by RobynSh** [comment]
Just noticed a typo in the shapefile realms ("Indomalya" instead of "Indomalaya"), so perhaps something like this:

#List terrestrial realms
Terrest <- c("Afrotropic", 
             "Antarctic",
             "Australasia", 
             "Indomalaya", 
             "Nearctic",
             "Neotropic", 
             "Oceania", 
             "Palearctic",
             "Palearctic")

#Shape file for bioregions
shape <- sf::st_read("data/teow_meow_simplified.shp")
shape$REALM <- dplyr::recode(shape$REALM, "Indomalya" = "Indomalaya")
shape <- shape %>%
  dplyr::rename(Bioregion = REALM) %>%
  dplyr::mutate(cols = as.factor(Bioregion), 
                Id = 1:length(Bioregion),
                PlotOrder = ifelse(Bioregion %in% Terrest, 2, 1)) %>%
  dplyr::arrange(PlotOrder)

**Comment by Bartesto** [comment]
Nice one @RobynSh! I had not used `recode` before and worked out how to pipe it with a `mutate` call. Also I made a new selection input so that the choices appear in alpha as does the table. Thought it might be more intuitive if you're searching for a favorite.
